### ISSUE TITLE
Dialog Editor issues

### ISSUE THREAD

**Issue by romanblanco** [ManageIQ/ui-components#219]
In this issue I'll keep a list of known issues in the dialog editor, I'll keep it as WIP, until I describe the issues properly with all the details.

bugs, missing features:

- [ ] missing spinner
- [x] update multiselect dropdown to save the default values as string ("value" - normal, "value1,value2" - multiselect
- [x] tag control without set automate methods gives errors (https://github.com/ManageIQ/ui-components/issues/173)
- [ ] flash messages (partially fixed in https://bugzilla.redhat.com/show_bug.cgi?id=1514117) - maybe display the error message on the save button with the same popup, we use for showing help info on dialog editor fields (maybe this could help: https://plnkr.co/edit/bdFVmZagG1APgKj0qGHp?p=info)
- [x] validations for fields (https://github.com/ManageIQ/manageiq-ui-classic/blob/33f26e217cce49a53de87733ce1de6b53a2e4a4e/app/controllers/miq_ae_customization_controller/dialogs.rb#L705, https://gitter.im/ManageIQ/manageiq/automate?at=5a258b6a71ad3f873665cb3f)
- [x] if the bootstrap switch is `undefined`, mark it as `false`
- [x] saving of intermediate state into localStorage
- [  ] validation - drag Tag Control into a empty dialog with a title - the validation says "Dialog needs to have a label" instead of "Category needs to be set for TagControl field". Setting a Category and un-setting it produces the correct error message.

refactoring:

- [ ] DRY code for dialog editor (there's a lot of copypasted code right now: https://github.com/ManageIQ/ui-components/pull/170#issuecomment-337713659)
- [x] correct naming in code (elements -> fields, box -> group, etc.)
- [x] https://github.com/ManageIQ/ui-components/issues/98
  

http://www.patternfly.org/pattern-library/content-views/canvas-view/

**Comment by skateman** [comment]
I went through both the codebase and these tasks and here is my refactoring idea that would help with these issues. First of all, I'd love to see a [single top-level component](https://github.com/ManageIQ/ui-components/pull/257) that can be dropped into any project by just injecting two services into it: one for [fetching/saving](https://github.com/ManageIQ/manageiq-ui-classic/pull/3414) the data from the network and one for holding the data (based on redux or just [keeping the current one](https://github.com/ManageIQ/ui-components/blob/75e29394f8914eb8988c705198b97d7f2274556f/src/dialog-editor/services/dialogEditorService.ts)). Any the other parts of the dialog editor should not be exposed externally.

The current component distribution is a little bit complex, it can be simplified like this:
```html
<dialog-editor>
  <dialog-editor-toolbox/>
  <dialog-editor-propertybox/>
  <dialog-editor-tab-list>
    <dialog-editor-tab>
      <dialog-editor-section>
        <dialog-editor-field/>
        ...
      </dialog-editor-section>
      ...
    </dialog-editor-tab>
    ...
  </dialog-editor-tab-list>
</dialog-editor>
```

As you can see I decomposed the current `<dialog-editor-boxes>` component into a more hierarchical structure where component sets have their own specific container components. In my opinion these container components should implement addig/deleting/reordering of their child components and allowing to edit their own properties (e.g. name). As these actions are very similar, this approach also DRYes the codebase a little bit.

As far as I see, the `toolbox` does not require any changes and the `propertybox` is just a fancy name for [the thing we want to have instead of modals](http://www.patternfly.org/pattern-library/content-views/canvas-view/).

**Comment by karelhala** [comment]
The codesnippet looks good, I like the idea of splitting current service into two, one for data and the other for data flow. We might simplify it even more by dropping `dialog-editor-tab-list` and `dialog-editor-section` and replacing them with classic `div` and `section`, because right now they just feel as proxies which would just pass data and events and no logic would be involved. But we'll see once we start coding.

**Comment by skateman** [comment]
@karelhala as I stated above, the `section` and `tab-list` components should be responsible for adding/deleting/reordering their child components. If we change them into standard HTML elements, we will have to put this functionality elsewhere...

**Comment by romanblanco** [comment]
@miq-bot remove_label stale

**Comment by martinpovolny** [comment]
@karelhala, @skateman: we should limit the investment into refactoring this. What we need is document what is does and rewrite it in react and while doing it keep one eye on PF4.

**Comment by romanblanco** [comment]
@miq-bot add_label dialog editor

**Comment by romanblanco** [comment]
@miq-bot remove_label stale
@miq-bot add_label pinned
