### ISSUE TITLE
Remove gray background from the GTLs / restyle quadicon wrapper

### ISSUE THREAD

**Issue by epwinchell** [ManageIQ/ui-components#406]
Now that the decision has been made to remove the old tile view (https://bugzilla.redhat.com/show_bug.cgi?id=1734182), it would be a great time to deal with another complication: When GTL was moved to Ui-components, a decision was made to wrap both the Tiles and Quadicons in a pf-card and display them on a gray background. This was not only inconsistent with list view but created enormous headaches on the classic side in rendering the gray background properly. 

<s>I would like to remove the card from the quads (see below)</s>, remove the gray background from that view and get rid of all the spaghetti logic on the classic side that will cause nothing but problems as we move forward.

Current
<img width="1087" alt="Screen Shot 2019-07-31 at 10 41 11 AM" src="https://user-images.githubusercontent.com/1287144/62222929-28044680-b382-11e9-80c7-a69b6438c7a6.png">

New
<img width="1266" alt="Screen Shot 2019-08-01 at 12 45 40 PM" src="https://user-images.githubusercontent.com/1287144/62311670-505f7400-b45a-11e9-9739-97f5de6a5990.png">

Current Listview
<img width="1110" alt="Screen Shot 2019-07-31 at 11 05 14 AM" src="https://user-images.githubusercontent.com/1287144/62223568-28e9a800-b383-11e9-8d2a-3dcef89e73b7.png">

**Comment by epwinchell** [comment]
@miq-bot assign @epwinchell

**Comment by epwinchell** [comment]
cc\ @himdel @martinpovolny @terezanovotna

**Comment by himdel** [comment]
I'm all for this,
we *still* have problems with code adding/removing the gray background.

**Comment by terezanovotna** [comment]
Hi @epwinchell. 

I am not against switching from gray to white background. But I don't like removing cards from each quadicon. I like how the card brings all the info together - the quad icons, the text above it. Can we keep the cards with the quad icon? maybe add some kind of a drop shadow so it is visible on the white background.

@karelhala has a good idea.

**Comment by karelhala** [comment]
I am strongly against removing cards from this view. I deliberately added them because it looked like on the proposed solution and honestly that doesn't look nice and user friendly. The worst part is that checkbox, we are forcing users to hit such a small target and on mobile devices that will lead to unwanted redirects (clicking on text will take you to detail).

This view without cards is not PF compliant, how about we remove that sandpaper styling and add slightly bigger box shadow?

![Peek 2019-08-01 09-57](https://user-images.githubusercontent.com/3439771/62276111-9d841b80-b443-11e9-8d50-73b05d4dfae0.gif)

**Comment by terezanovotna** [comment]
I like what Karel suggested.

**Comment by epwinchell** [comment]
@terezanovotna @karelhala Sounds good

**Comment by himdel** [comment]
Closed by https://github.com/ManageIQ/ui-components/pull/409 (and https://github.com/ManageIQ/manageiq-ui-classic/pull/5917) :)
